services:
  db_test_aplhi:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: adk_sessions
      POSTGRES_USER: adk_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adk_user -d adk_sessions"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_test_aplhi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOME=/root            # tu variable de entorno local
    depends_on:
      db_test_aplhi:
        condition: service_healthy


volumes:
  pgdata:
